name: add-label-to-issues

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  add-label-to-issues:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: npm ci

      - name: Label issues
        run: npm run add-label-to-issues
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ISSUE_LABEL: "needs triage"
          ISSUE_QUERY: org:mdn is:issue is:public is:open no:label -repo:mdn/browser-compat-data -repo:mdn/curriculum -repo:mdn/translated-content sort:created-asc
