name: add-to-project

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  add-to-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: npm ci

      - name: Issue triage
        run: npm run add-to-project
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ISSUE_PROJECT_DELAY: 3
          ISSUE_PROJECT_OWNER: mdn
          ISSUE_PROJECT_NUMBER: 33
          ISSUE_PROJECT_QUERY: org:mdn is:issue is:public is:open archived:false label:"needs triage" -repo:mdn/browser-compat-data -repo:mdn/translated-content sort:created-asc

      - name: Content issues
        run: npm run add-to-project
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ISSUE_PROJECT_OWNER: mdn
          ISSUE_PROJECT_NUMBER: 37
          ISSUE_PROJECT_QUERY: 'repo:mdn/content is:issue is:public is:open label:"effort: small","effort: medium","effort: large" sort:created-asc'

      - name: Engineering issues
        run: npm run add-to-project
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ISSUE_PROJECT_OWNER: mdn
          ISSUE_PROJECT_NUMBER: 36
          ISSUE_PROJECT_QUERY: repo:mdn/yari is:issue is:public is:open label:p0,p1,p2,p3,p4 sort:created-asc

      - name: Product issues
        run: npm run add-to-project
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ISSUE_PROJECT_OWNER: mdn
          ISSUE_PROJECT_NUMBER: 38
          ISSUE_PROJECT_QUERY: 'org:mdn is:issue is:public is:open archived:false label:"Resource: Product","Resource: UX",ux sort:created-asc'

      - name: Content PRs
        run: npm run add-to-project
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ISSUE_PROJECT_OWNER: mdn
          ISSUE_PROJECT_NUMBER: 39
          ISSUE_PROJECT_QUERY: |
            org:mdn is:pr is:public is:open archived:false sort:created-asc team-review-requested:mdn/core-yari-content
            org:mdn is:pr is:public is:open archived:false sort:created-asc user-review-requested:bsmth
            org:mdn is:pr is:public is:open archived:false sort:created-asc user-review-requested:dipikabh
            org:mdn is:pr is:public is:open archived:false sort:created-asc user-review-requested:Rumyra
            org:mdn is:pr is:public is:open archived:false sort:created-asc user-review-requested:zfox23

      - name: Engineering PRs
        run: npm run add-to-project
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ISSUE_PROJECT_OWNER: mdn
          ISSUE_PROJECT_NUMBER: 40
          ISSUE_PROJECT_QUERY: |
            org:mdn is:pr is:public is:open archived:false sort:created-asc team-review-requested:mdn/core-dev
            org:mdn is:pr is:public is:open archived:false sort:created-asc user-review-requested:caugner
            org:mdn is:pr is:public is:open archived:false sort:created-asc user-review-requested:fiji-flo
            org:mdn is:pr is:public is:open archived:false sort:created-asc user-review-requested:LeoMcA
            repo:mdn/yari is:pr is:public is:open archived:false sort:created-asc -author:app/dependabot review:none
